#!/bin/bash

#- update permissions for cemac arc4 directory
#  make things group writeable where appropriate
#  make things read only where appropriate

# check CEMAC_DIR variable:
if [ -z "${CEMAC_DIR}" ] ; then
  echo "please check CEMAC_DIR variable"
  exit
fi

# check CEMAC_DIR directory:
if [ ! -d "${CEMAC_DIR}" ] ; then
  echo "${CEMAC_DIR} directory does not appear to exist"
  exit
fi

# CEMAC data should be owned by group ear-cemac, and group writeable:
chgrp ear-cemac ${CEMAC_DIR}
chmod 2775 ${CEMAC_DIR}

# Top level files which should be group writeable:
chgrp ear-cemac \
  ${CEMAC_DIR}/{cemac.sh,cemac.csh,LICENSE,README.md,__update_permissions}
chmod g+rwX \
  ${CEMAC_DIR}/{cemac.sh,cemac.csh,LICENSE,README.md,__update_permissions}

# git directory:
GIT_DIR="${CEMAC_DIR}/.git"

# make git directory group writeable:
chgrp -R ear-cemac ${GIT_DIR}
find ${GIT_DIR} -type d -exec chmod g+s '{}' \;
chmod -R g+rwX ${GIT_DIR}

# software directory:
SOFTWARE_DIR="${CEMAC_DIR}/software"

# make build directories group writeable:
chgrp -R ear-cemac ${SOFTWARE_DIR}
find ${SOFTWARE_DIR} -type d -exec chmod g+s '{}' \;
chmod -R g+rwX ${SOFTWARE_DIR}/build

# make application parent directories group writeable:
chmod g+rwX ${SOFTWARE_DIR}/apps/*/*
chmod g+rwX ${SOFTWARE_DIR}/compilers/*/*
chmod g+rwX ${SOFTWARE_DIR}/libraries/*/*
# make installed apps read only:
chmod -R a-w ${SOFTWARE_DIR}/apps/*/*/*
chmod -R a-w ${SOFTWARE_DIR}/compilers/*/*/*
chmod -R a-w ${SOFTWARE_DIR}/libraries/*/*/*

# modulefiles ... :
chmod g+rwX ${SOFTWARE_DIR}/modulefiles

# cron directory:
CRON_DIR="${CEMAC_DIR}/cron"

# make cron directory group writeable:
chgrp -R ear-cemac ${CRON_DIR}
find ${CRON_DIR} -type d -exec chmod g+s '{}' \;
chmod -R g+rwX ${CRON_DIR}
